### ISSUE TITLE
Store problem datas in a DB

### ISSUE THREAD

**Issue by fraknoiadam** [a-gondolkodas-orome/durer-aion#120]
Scope: store problem text in the current POSTGRESQL, instead of typescript file.

- [ ] Make a frontend page in admin page for uploading:
  - Make a selector for category selection: C, D or E.
  - Upload the problems as a json or create an empty 
- [ ] Make the following API points:
  - `/upload-`
- [ ]

**Comment by fraknoiadam** [comment]
Old YAML format?
```
relay_problems:
  C:
    - problemText: "2 + 2 = ?"
      answer: 4
      points: 1
    - problemText: "10 - 3 = ?"
      answer: 7
      points: 1
    - problemText: "3 * 3 = ?"
      answer: 9
      points: 1
  D:
    - problemText: |
        "5 * 6 = ?
        
        What is the product?"
      answer: 30
      points: 2
      url: "multiplication.png"
    - problemText: "12 / 4 = ?"
      answer: 3
      points: 2
    - problemText: "15 + 7 = ?"
      answer: 22
      points: 2
  E:
    - problemText: "What is the derivative of x^2?"
      answer: 2
      points: 3
    - problemText: "Integrate 2x dx."
      answer: "x^2 + C"
      points: 3
    - problemText: "Solve for x: 3x + 5 = 20"
      answer: 5
      points: 3
```
